# Generated by Django 3.2.25 on 2024-05-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('popularidade', models.IntegerField(default=0)),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('generos', models.ManyToManyField(to='recommendations.Genero')),
            ],
        ),
    ]
